In [2]:
import sqlite3
from pathlib import Path
import pandas as pd

In [3]:
DB_PATH = Path("../../data/data_lakehouse.db").resolve()
conn = sqlite3.connect(DB_PATH)

dim_aluno = pd.read_sql("SELECT * FROM dim_aluno", conn)
fato_desempenho = pd.read_sql("SELECT * FROM fato_desempenho", conn)

df = dim_aluno.merge(fato_desempenho, on="StudentID", how="inner")

df.head()

,StudentID,Age,Gender,Gender_label,ParentalEducation,ParentalEducation_label,ParentalSupport,ParentalSupport_label,StudyTimeWeekly,Absences,...,Extracurricular_label,Sports,Sports_label,Music,Music_label,Volunteering,Volunteering_label,GPA,GradeClass,GradeClass_label
0,1001,17,1,Feminino,2,Faculdade Incompleta,2,Moderado,19.833723,7,...,Não,0,Não,1,Sim,0,Não,2.929196,2,C (2.5 <= GPA < 3.0)
1,1002,18,0,Masculino,1,Ensino Médio,1,Baixo,15.408756,0,...,Não,0,Não,0,Não,0,Não,3.042915,1,B (3.0 <= GPA < 3.5)
2,1003,15,0,Masculino,3,Bacharelado,2,Moderado,4.210570,26,...,Não,0,Não,0,Não,0,Não,0.112602,4,F (GPA < 2.0)
3,1004,17,1,Feminino,3,Bacharelado,3,Alto,10.028829,14,...,Sim,0,Não,0,Não,0,Não,2.054218,3,D (2.0 <= GPA < 2.5)
4,1005,17,1,Feminino,2,Faculdade Incompleta,3,Alto,4.672495,17,...,Não,0,Não,0,Não,0,Não,1.288061,4,F (GPA < 2.0)

In [4]:
dim_aluno.head()

,StudentID,Age,Gender,Gender_label,ParentalEducation,ParentalEducation_label,ParentalSupport,ParentalSupport_label
0,1001,17,1,Feminino,2,Faculdade Incompleta,2,Moderado
1,1002,18,0,Masculino,1,Ensino Médio,1,Baixo
2,1003,15,0,Masculino,3,Bacharelado,2,Moderado
3,1004,17,1,Feminino,3,Bacharelado,3,Alto
4,1005,17,1,Feminino,2,Faculdade Incompleta,3,Alto

In [5]:
fato_desempenho.head()

,StudentID,StudyTimeWeekly,Absences,Tutoring,Tutoring_label,Extracurricular,Extracurricular_label,Sports,Sports_label,Music,Music_label,Volunteering,Volunteering_label,GPA,GradeClass,GradeClass_label
0,1001,19.833723,7,1,Sim,0,Não,0,Não,1,Sim,0,Não,2.929196,2,C (2.5 <= GPA < 3.0)
1,1002,15.408756,0,0,Não,0,Não,0,Não,0,Não,0,Não,3.042915,1,B (3.0 <= GPA < 3.5)
2,1003,4.210570,26,0,Não,0,Não,0,Não,0,Não,0,Não,0.112602,4,F (GPA < 2.0)
3,1004,10.028829,14,0,Não,1,Sim,0,Não,0,Não,0,Não,2.054218,3,D (2.0 <= GPA < 2.5)
4,1005,4.672495,17,1,Sim,0,Não,0,Não,0,Não,0,Não,1.288061,4,F (GPA < 2.0)

In [6]:
df

,StudentID,Age,Gender,Gender_label,ParentalEducation,ParentalEducation_label,ParentalSupport,ParentalSupport_label,StudyTimeWeekly,Absences,...,Extracurricular_label,Sports,Sports_label,Music,Music_label,Volunteering,Volunteering_label,GPA,GradeClass,GradeClass_label
0,1001,17,1,Feminino,2,Faculdade Incompleta,2,Moderado,19.833723,7,...,Não,0,Não,1,Sim,0,Não,2.929196,2,C (2.5 <= GPA < 3.0)
1,1002,18,0,Masculino,1,Ensino Médio,1,Baixo,15.408756,0,...,Não,0,Não,0,Não,0,Não,3.042915,1,B (3.0 <= GPA < 3.5)
2,1003,15,0,Masculino,3,Bacharelado,2,Moderado,4.210570,26,...,Não,0,Não,0,Não,0,Não,0.112602,4,F (GPA < 2.0)
3,1004,17,1,Feminino,3,Bacharelado,3,Alto,10.028829,14,...,Sim,0,Não,0,Não,0,Não,2.054218,3,D (2.0 <= GPA < 2.5)
4,1005,17,1,Feminino,2,Faculdade Incompleta,3,Alto,4.672495,17,...,Não,0,Não,0,Não,0,Não,1.288061,4,F (GPA < 2.0)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,Feminino,3,Bacharelado,4,Muito Alto,10.680555,2,...,Sim,0,Não,0,Não,0,Não,3.455509,0,A (GPA >= 3.5)
2388,3389,17,0,Masculino,1,Ensino Médio,4,Muito Alto,7.583217,4,...,Não,1,Sim,0,Não,0,Não,3.279150,4,F (GPA < 2.0)
2389,3390,16,1,Feminino,2,Faculdade Incompleta,2,Moderado,6.805500,20,...,Não,0,Não,0,Não,1,Sim,1.142333,2,C (2.5 <= GPA < 3.0)
2390,3391,16,1,Feminino,0,Nenhum,2,Moderado,12.416653,17,...,Não,1,Sim,1,Sim,0,Não,1.803297,1,B (3.0 <= GPA < 3.5)
2391,3392,16,1,Feminino,2,Faculdade Incompleta,2,Moderado,17.819907,13,...,Não,0,Não,0,Não,1,Sim,2.140014,1,B (3.0 <= GPA < 3.5)

In [7]:

df=pd.get_dummies(df,columns=['ParentalEducation_label'],drop_first=True)
df.head()

,StudentID,Age,Gender,Gender_label,ParentalEducation,ParentalSupport,ParentalSupport_label,StudyTimeWeekly,Absences,Tutoring,...,Music_label,Volunteering,Volunteering_label,GPA,GradeClass,GradeClass_label,ParentalEducation_label_Ensino Médio,ParentalEducation_label_Faculdade Incompleta,ParentalEducation_label_Nenhum,ParentalEducation_label_Pós-Graduação
0,1001,17,1,Feminino,2,2,Moderado,19.833723,7,1,...,Sim,0,Não,2.929196,2,C (2.5 <= GPA < 3.0),False,True,False,False
1,1002,18,0,Masculino,1,1,Baixo,15.408756,0,0,...,Não,0,Não,3.042915,1,B (3.0 <= GPA < 3.5),True,False,False,False
2,1003,15,0,Masculino,3,2,Moderado,4.210570,26,0,...,Não,0,Não,0.112602,4,F (GPA < 2.0),False,False,False,False
3,1004,17,1,Feminino,3,3,Alto,10.028829,14,0,...,Não,0,Não,2.054218,3,D (2.0 <= GPA < 2.5),False,False,False,False
4,1005,17,1,Feminino,2,3,Alto,4.672495,17,1,...,Não,0,Não,1.288061,4,F (GPA < 2.0),False,True,False,False

In [8]:
df=pd.get_dummies(df,columns=['ParentalSupport_label'], drop_first=True)
df.head()

,StudentID,Age,Gender,Gender_label,ParentalEducation,ParentalSupport,StudyTimeWeekly,Absences,Tutoring,Tutoring_label,...,GradeClass,GradeClass_label,ParentalEducation_label_Ensino Médio,ParentalEducation_label_Faculdade Incompleta,ParentalEducation_label_Nenhum,ParentalEducation_label_Pós-Graduação,ParentalSupport_label_Baixo,ParentalSupport_label_Moderado,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum
0,1001,17,1,Feminino,2,2,19.833723,7,1,Sim,...,2,C (2.5 <= GPA < 3.0),False,True,False,False,False,True,False,False
1,1002,18,0,Masculino,1,1,15.408756,0,0,Não,...,1,B (3.0 <= GPA < 3.5),True,False,False,False,True,False,False,False
2,1003,15,0,Masculino,3,2,4.210570,26,0,Não,...,4,F (GPA < 2.0),False,False,False,False,False,True,False,False
3,1004,17,1,Feminino,3,3,10.028829,14,0,Não,...,3,D (2.0 <= GPA < 2.5),False,False,False,False,False,False,False,False
4,1005,17,1,Feminino,2,3,4.672495,17,1,Sim,...,4,F (GPA < 2.0),False,True,False,False,False,False,False,False

In [9]:
df=pd.get_dummies(df, columns=['Age'], drop_first=True)
df

,StudentID,Gender,Gender_label,ParentalEducation,ParentalSupport,StudyTimeWeekly,Absences,Tutoring,Tutoring_label,Extracurricular,...,ParentalEducation_label_Faculdade Incompleta,ParentalEducation_label_Nenhum,ParentalEducation_label_Pós-Graduação,ParentalSupport_label_Baixo,ParentalSupport_label_Moderado,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18
0,1001,1,Feminino,2,2,19.833723,7,1,Sim,0,...,True,False,False,False,True,False,False,False,True,False
1,1002,0,Masculino,1,1,15.408756,0,0,Não,0,...,False,False,False,True,False,False,False,False,False,True
2,1003,0,Masculino,3,2,4.210570,26,0,Não,0,...,False,False,False,False,True,False,False,False,False,False
3,1004,1,Feminino,3,3,10.028829,14,0,Não,1,...,False,False,False,False,False,False,False,False,True,False
4,1005,1,Feminino,2,3,4.672495,17,1,Sim,0,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,1,Feminino,3,4,10.680555,2,0,Não,1,...,False,False,False,False,False,True,False,False,False,True
2388,3389,0,Masculino,1,4,7.583217,4,1,Sim,0,...,False,False,False,False,False,True,False,False,True,False
2389,3390,1,Feminino,2,2,6.805500,20,0,Não,0,...,True,False,False,False,True,False,False,True,False,False
2390,3391,1,Feminino,0,2,12.416653,17,0,Não,0,...,False,True,False,False,True,False,False,True,False,False
2391,3392,1,Feminino,2,2,17.819907,13,0,Não,0,...,True,False,False,False,True,False,False,True,False,False

In [10]:
df['AbscencesGroup'] = pd.cut(df['Absences'], bins=[0,10,20,30], labels=['Baixa','Media','Alta'], include_lowest=True)
df

,StudentID,Gender,Gender_label,ParentalEducation,ParentalSupport,StudyTimeWeekly,Absences,Tutoring,Tutoring_label,Extracurricular,...,ParentalEducation_label_Nenhum,ParentalEducation_label_Pós-Graduação,ParentalSupport_label_Baixo,ParentalSupport_label_Moderado,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup
0,1001,1,Feminino,2,2,19.833723,7,1,Sim,0,...,False,False,False,True,False,False,False,True,False,Baixa
1,1002,0,Masculino,1,1,15.408756,0,0,Não,0,...,False,False,True,False,False,False,False,False,True,Baixa
2,1003,0,Masculino,3,2,4.210570,26,0,Não,0,...,False,False,False,True,False,False,False,False,False,Alta
3,1004,1,Feminino,3,3,10.028829,14,0,Não,1,...,False,False,False,False,False,False,False,True,False,Media
4,1005,1,Feminino,2,3,4.672495,17,1,Sim,0,...,False,False,False,False,False,False,False,True,False,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,1,Feminino,3,4,10.680555,2,0,Não,1,...,False,False,False,False,True,False,False,False,True,Baixa
2388,3389,0,Masculino,1,4,7.583217,4,1,Sim,0,...,False,False,False,False,True,False,False,True,False,Baixa
2389,3390,1,Feminino,2,2,6.805500,20,0,Não,0,...,False,False,False,True,False,False,True,False,False,Media
2390,3391,1,Feminino,0,2,12.416653,17,0,Não,0,...,True,False,False,True,False,False,True,False,False,Media
2391,3392,1,Feminino,2,2,17.819907,13,0,Não,0,...,False,False,False,True,False,False,True,False,False,Media

In [11]:
df = pd.get_dummies(df,columns=['AbscencesGroup'], drop_first=True)
df

,StudentID,Gender,Gender_label,ParentalEducation,ParentalSupport,StudyTimeWeekly,Absences,Tutoring,Tutoring_label,Extracurricular,...,ParentalEducation_label_Pós-Graduação,ParentalSupport_label_Baixo,ParentalSupport_label_Moderado,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup_Media,AbscencesGroup_Alta
0,1001,1,Feminino,2,2,19.833723,7,1,Sim,0,...,False,False,True,False,False,False,True,False,False,False
1,1002,0,Masculino,1,1,15.408756,0,0,Não,0,...,False,True,False,False,False,False,False,True,False,False
2,1003,0,Masculino,3,2,4.210570,26,0,Não,0,...,False,False,True,False,False,False,False,False,False,True
3,1004,1,Feminino,3,3,10.028829,14,0,Não,1,...,False,False,False,False,False,False,True,False,True,False
4,1005,1,Feminino,2,3,4.672495,17,1,Sim,0,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,1,Feminino,3,4,10.680555,2,0,Não,1,...,False,False,False,True,False,False,False,True,False,False
2388,3389,0,Masculino,1,4,7.583217,4,1,Sim,0,...,False,False,False,True,False,False,True,False,False,False
2389,3390,1,Feminino,2,2,6.805500,20,0,Não,0,...,False,False,True,False,False,True,False,False,True,False
2390,3391,1,Feminino,0,2,12.416653,17,0,Não,0,...,False,False,True,False,False,True,False,False,True,False
2391,3392,1,Feminino,2,2,17.819907,13,0,Não,0,...,False,False,True,False,False,True,False,False,True,False

In [12]:
df['StudyGroup'] = pd.cut(df['StudyTimeWeekly'], bins=[0,5,10,15,20], labels=['Muito baixo', 'Baixa', 'Média', 'Alta'], include_lowest=True)
df

,StudentID,Gender,Gender_label,ParentalEducation,ParentalSupport,StudyTimeWeekly,Absences,Tutoring,Tutoring_label,Extracurricular,...,ParentalSupport_label_Baixo,ParentalSupport_label_Moderado,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup_Media,AbscencesGroup_Alta,StudyGroup
0,1001,1,Feminino,2,2,19.833723,7,1,Sim,0,...,False,True,False,False,False,True,False,False,False,Alta
1,1002,0,Masculino,1,1,15.408756,0,0,Não,0,...,True,False,False,False,False,False,True,False,False,Alta
2,1003,0,Masculino,3,2,4.210570,26,0,Não,0,...,False,True,False,False,False,False,False,False,True,Muito baixo
3,1004,1,Feminino,3,3,10.028829,14,0,Não,1,...,False,False,False,False,False,True,False,True,False,Média
4,1005,1,Feminino,2,3,4.672495,17,1,Sim,0,...,False,False,False,False,False,True,False,True,False,Muito baixo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,1,Feminino,3,4,10.680555,2,0,Não,1,...,False,False,True,False,False,False,True,False,False,Média
2388,3389,0,Masculino,1,4,7.583217,4,1,Sim,0,...,False,False,True,False,False,True,False,False,False,Baixa
2389,3390,1,Feminino,2,2,6.805500,20,0,Não,0,...,False,True,False,False,True,False,False,True,False,Baixa
2390,3391,1,Feminino,0,2,12.416653,17,0,Não,0,...,False,True,False,False,True,False,False,True,False,Média
2391,3392,1,Feminino,2,2,17.819907,13,0,Não,0,...,False,True,False,False,True,False,False,True,False,Alta

In [13]:
df = pd.get_dummies(df, columns=['StudyGroup'], drop_first=True)
df

,StudentID,Gender,Gender_label,ParentalEducation,ParentalSupport,StudyTimeWeekly,Absences,Tutoring,Tutoring_label,Extracurricular,...,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup_Media,AbscencesGroup_Alta,StudyGroup_Baixa,StudyGroup_Média,StudyGroup_Alta
0,1001,1,Feminino,2,2,19.833723,7,1,Sim,0,...,False,False,False,True,False,False,False,False,False,True
1,1002,0,Masculino,1,1,15.408756,0,0,Não,0,...,False,False,False,False,True,False,False,False,False,True
2,1003,0,Masculino,3,2,4.210570,26,0,Não,0,...,False,False,False,False,False,False,True,False,False,False
3,1004,1,Feminino,3,3,10.028829,14,0,Não,1,...,False,False,False,True,False,True,False,False,True,False
4,1005,1,Feminino,2,3,4.672495,17,1,Sim,0,...,False,False,False,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,1,Feminino,3,4,10.680555,2,0,Não,1,...,True,False,False,False,True,False,False,False,True,False
2388,3389,0,Masculino,1,4,7.583217,4,1,Sim,0,...,True,False,False,True,False,False,False,True,False,False
2389,3390,1,Feminino,2,2,6.805500,20,0,Não,0,...,False,False,True,False,False,True,False,True,False,False
2390,3391,1,Feminino,0,2,12.416653,17,0,Não,0,...,False,False,True,False,False,True,False,False,True,False
2391,3392,1,Feminino,2,2,17.819907,13,0,Não,0,...,False,False,True,False,False,True,False,False,False,True

In [14]:
print(df.columns)

Index(['StudentID', 'Gender', 'Gender_label', 'ParentalEducation',
       'ParentalSupport', 'StudyTimeWeekly', 'Absences', 'Tutoring',
       'Tutoring_label', 'Extracurricular', 'Extracurricular_label', 'Sports',
       'Sports_label', 'Music', 'Music_label', 'Volunteering',
       'Volunteering_label', 'GPA', 'GradeClass', 'GradeClass_label',
       'ParentalEducation_label_Ensino Médio',
       'ParentalEducation_label_Faculdade Incompleta',
       'ParentalEducation_label_Nenhum',
       'ParentalEducation_label_Pós-Graduação', 'ParentalSupport_label_Baixo',
       'ParentalSupport_label_Moderado', 'ParentalSupport_label_Muito Alto',
       'ParentalSupport_label_Nenhum', 'Age_16', 'Age_17', 'Age_18',
       'AbscencesGroup_Media', 'AbscencesGroup_Alta', 'StudyGroup_Baixa',
       'StudyGroup_Média', 'StudyGroup_Alta'],
      dtype='object')

In [15]:
df = df.drop(columns={
    'StudentID',
    'Gender_label',
    'ParentalEducation',
    'Absences',
    'ParentalSupport',
    'Tutoring_label',
    'Extracurricular_label',
    'Sports_label',
    'Music_label',
    'Volunteering_label',
    'GradeClass_label',
    'StudyTimeWeekly',
    'GPA'
})

df.head()

,Gender,Tutoring,Extracurricular,Sports,Music,Volunteering,GradeClass,ParentalEducation_label_Ensino Médio,ParentalEducation_label_Faculdade Incompleta,ParentalEducation_label_Nenhum,...,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup_Media,AbscencesGroup_Alta,StudyGroup_Baixa,StudyGroup_Média,StudyGroup_Alta
0,1,1,0,0,1,0,2,False,True,False,...,False,False,False,True,False,False,False,False,False,True
1,0,0,0,0,0,0,1,True,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,0,0,0,0,0,4,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,1,0,1,0,0,0,3,False,False,False,...,False,False,False,True,False,True,False,False,True,False
4,1,1,0,0,0,0,4,False,True,False,...,False,False,False,True,False,True,False,False,False,False

In [16]:
print(df.columns)

Index(['Gender', 'Tutoring', 'Extracurricular', 'Sports', 'Music',
       'Volunteering', 'GradeClass', 'ParentalEducation_label_Ensino Médio',
       'ParentalEducation_label_Faculdade Incompleta',
       'ParentalEducation_label_Nenhum',
       'ParentalEducation_label_Pós-Graduação', 'ParentalSupport_label_Baixo',
       'ParentalSupport_label_Moderado', 'ParentalSupport_label_Muito Alto',
       'ParentalSupport_label_Nenhum', 'Age_16', 'Age_17', 'Age_18',
       'AbscencesGroup_Media', 'AbscencesGroup_Alta', 'StudyGroup_Baixa',
       'StudyGroup_Média', 'StudyGroup_Alta'],
      dtype='object')

In [17]:
bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols].head()

,ParentalEducation_label_Ensino Médio,ParentalEducation_label_Faculdade Incompleta,ParentalEducation_label_Nenhum,ParentalEducation_label_Pós-Graduação,ParentalSupport_label_Baixo,ParentalSupport_label_Moderado,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup_Media,AbscencesGroup_Alta,StudyGroup_Baixa,StudyGroup_Média,StudyGroup_Alta
0,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,True
1,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True
2,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False
4,False,True,False,False,False,False,False,False,False,True,False,True,False,False,False,False

In [18]:
df[bool_cols] = df[bool_cols].astype(int)
df

,Gender,Tutoring,Extracurricular,Sports,Music,Volunteering,GradeClass,ParentalEducation_label_Ensino Médio,ParentalEducation_label_Faculdade Incompleta,ParentalEducation_label_Nenhum,...,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup_Media,AbscencesGroup_Alta,StudyGroup_Baixa,StudyGroup_Média,StudyGroup_Alta
0,1,1,0,0,1,0,2,0,1,0,...,0,0,0,1,0,0,0,0,0,1
1,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,0,0,0,0,0,4,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,1,0,1,0,0,0,3,0,0,0,...,0,0,0,1,0,1,0,0,1,0
4,1,1,0,0,0,0,4,0,1,0,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,1,0,1,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2388,0,1,0,1,0,0,4,1,0,0,...,1,0,0,1,0,0,0,1,0,0
2389,1,0,0,0,0,1,2,0,1,0,...,0,0,1,0,0,1,0,1,0,0
2390,1,0,0,1,1,0,1,0,0,1,...,0,0,1,0,0,1,0,0,1,0
2391,1,0,0,0,0,1,1,0,1,0,...,0,0,1,0,0,1,0,0,0,1

In [19]:
df.head()

,Gender,Tutoring,Extracurricular,Sports,Music,Volunteering,GradeClass,ParentalEducation_label_Ensino Médio,ParentalEducation_label_Faculdade Incompleta,ParentalEducation_label_Nenhum,...,ParentalSupport_label_Muito Alto,ParentalSupport_label_Nenhum,Age_16,Age_17,Age_18,AbscencesGroup_Media,AbscencesGroup_Alta,StudyGroup_Baixa,StudyGroup_Média,StudyGroup_Alta
0,1,1,0,0,1,0,2,0,1,0,...,0,0,0,1,0,0,0,0,0,1
1,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,0,0,0,0,0,4,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,1,0,1,0,0,0,3,0,0,0,...,0,0,0,1,0,1,0,0,1,0
4,1,1,0,0,0,0,4,0,1,0,...,0,0,0,1,0,1,0,0,0,0

In [20]:
df.to_csv('../../data/input.csv',index=False)